apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 8 }}
rules:
  - apiGroups: ["pkg.crossplane.io"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]