apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rolebinding
  namespace: {{ .Release.Namespace  }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}-rolebinding
    app.kubernetes.io/component: control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.serviceAccount.name }}